---
# Setup folders
- name: DEPLOY | Raiz da App {{ ansistrano_deploy_to }}
  file: 
    state: directory 
    path: "{{ ansistrano_deploy_to }}"

#- name: DEPLOY | Definindo a Release
- command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: DEPLOY | Release Path {{ ansistrano_releases_path.stdout }}
  file: 
    state: directory 
    path: "{{ ansistrano_releases_path.stdout }}"

- name: DEPLOY | Shared Path {{ ansistrano_deploy_to }}/shared
  command: echo "{{ ansistrano_deploy_to }}/shared"
  register: ansistrano_shared_path

- name: DEPLOY | Verificando a Shared Path {{ ansistrano_shared_path.stdout }}
  file: 
    state: directory 
    path: "{{ ansistrano_shared_path.stdout }}"
