version: "3.9"
    
services:
  db:
    container_name: wordpress-db
    image: mysql:5.7
    volumes:
      - /opt/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    
  wordpress:
    depends_on:
      - db
    container_name: wordpress-app
    image: wordpress:php7.4
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_database
      WORDPRESS_TABLE_PREFIX: wp_
      MUST_WAIT_DB: "10"
    volumes:
      - /var/deploy/lab-wordpress/current:/var/www/html